### ISSUE TITLE
Cant resize image get 500

### ISSUE THREAD

**Issue by yurabysaha** [cagataygurturk/image-resizer-service#2]
Hi i cant resize my image get 500 all time. this is error from log

2018-08-29T08:08:47.400Z c140e36b-ab62-11e8-bb5f-5f46c0f12ae0 Error: Command failed: convert: unable to open image `/tmp/resized.city-plus.a/download.png.10.10': No such file or directory @ error/blob.c/OpenBlob/2643.
convert: WriteBlob Failed `/tmp/resized.city-plus.a/download.png.10.10' @ error/png.c/MagickPNGErrorHandler/1751.

at ChildProcess.<anonymous> (/var/task/index.js:1:2652)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:886:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

But i can get origin picture. without params width and height

**Comment by yurabysaha** [comment]
Ohhh if i copy solution from previous bug all works good.
Could you please update your code. Thx

**Comment by cagataygurturk** [comment]
Hello, thanks for the feedback. I've released a new version that fixed also this problem.
